name: ci:deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4
        with:
          fetch-depth: 1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses:  lemonarc/jekyll-action@1.0.0
#      - name: deploy
#        uses: SamKirkland/FTP-Deploy-Action@4.0.0
#        with:
#          server: ${{secrets.FTP_SERVER}}
#          username: ${{secrets.FTP_USERNAME}}@{{secrets.FTP_SERVER}}
#          password: ${{secrets.FTP_PASSWORD}}
#          local-dir: ./_site/
